### ISSUE TITLE
rolldown-vite crashing with vite-plugin-pwa used in Yarn PnP

### ISSUE THREAD

**Issue by wojtekmaj** [vitejs/rolldown-vite#324]
### Describe the regression

Builds consistently fail when using Yarn PnP when import from `virtual:pwa-register` is present.

### Reproduction

I'm unable to provide Stackblitz playground - corepack not enabled in Stackblitz.

[repro.zip](https://github.com/user-attachments/files/21178968/repro.zip)

### Expected Behavior

Builds not crashing

### Actual Behavior

Build crashing (see logs)

### Steps to Reproduce

1. Install a project using Yarn (tested: 4.9.1) using PnP mode
1. Build the app

### System Info

```shell
System:
    OS: macOS 15.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 535.63 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.3.0 - /private/var/folders/9x/22rs089d2t31txstbb0vnl1r0000gp/T/xfs-35d15554/node
    Yarn: 4.9.1 - /private/var/folders/9x/22rs089d2t31txstbb0vnl1r0000gp/T/xfs-35d15554/yarn
    npm: 11.4.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 138.0.7204.101
    Safari: 18.5
```

### Used Package Manager

yarn

### Logs

<details>
<summary>Click to expand!</summary>
```shell
  vite:config config file loaded in 16.19ms +0ms
  vite:env loading env files: [
  vite:env   '/Users/wojciech.maj/Downloads/repro/.env',
  vite:env   '/Users/wojciech.maj/Downloads/repro/.env.local',
  vite:env   '/Users/wojciech.maj/Downloads/repro/.env.production',
  vite:env   '/Users/wojciech.maj/Downloads/repro/.env.production.local'
  vite:env ] +0ms
  vite:env env files loaded in 0.28ms +0ms
  vite:env using resolved env: {} +1ms
  vite:config using resolved config: {
  vite:config   plugins: [
  vite:config     'vite:watch-package-data',
  vite:config     'alias',
  vite:config     'vite-plugin-pwa',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:oxc',
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vite:wasm-fallback',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:build-html',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:force-systemjs-wrap-complete',
  vite:config     'vite:rollup-options-plugins',
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',
  vite:config     'vite-plugin-pwa:info',
  vite:config     'vite-plugin-pwa:build',
  vite:config     'vite-plugin-pwa:pwa-assets',
  vite:config     'vite:build-import-analysis',
  vite:config     'vite:oxc-transpile',
  vite:config     'vite:terser',
  vite:config     'vite:manifest',
  vite:config     'vite:ssr-manifest',
  vite:config     'vite:reporter',
  vite:config     'builtin:load-fallback'
  vite:config   ],
  vite:config   build: {
  vite:config     target: [ 'chrome107', 'edge107', 'firefox104', 'safari16' ],
  vite:config     polyfillModulePreload: true,
  vite:config     modulePreload: { polyfill: true },
  vite:config     outDir: 'dist',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     sourcemap: false,
  vite:config     terserOptions: {},
  vite:config     rollupOptions: { platform: 'browser' },
  vite:config     commonjsOptions: { include: [ /node_modules/ ], extensions: [ '.js', '.cjs' ] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [ /node_modules/ ] },
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     copyPublicDir: true,
  vite:config     manifest: false,
  vite:config     lib: false,
  vite:config     ssrManifest: false,
  vite:config     ssrEmitAssets: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     cssCodeSplit: true,
  vite:config     minify: 'oxc',
  vite:config     ssr: false,
  vite:config     emitAssets: true,
  vite:config     createEnvironment: [Function: createEnvironment],
  vite:config     cssTarget: [ 'chrome107', 'edge107', 'firefox104', 'safari16' ],
  vite:config     cssMinify: true
  vite:config   },
  vite:config   ssr: {
  vite:config     target: 'node',
  vite:config     optimizeDeps: {
  vite:config       esbuildOptions: { preserveSymlinks: false },
  vite:config       include: [],
  vite:config       exclude: [],
  vite:config       needsInterop: [],
  vite:config       rollupOptions: { resolve: { symlinks: true } },
  vite:config       extensions: [],
  vite:config       holdUntilCrawlEnd: true,
  vite:config       force: false,
  vite:config       noDiscovery: true
  vite:config     },
  vite:config     noExternal: [ 'workbox-window' ],
  vite:config     external: [],
  vite:config     resolve: {
  vite:config       conditions: [ 'module', 'node', 'development|production' ],
  vite:config       externalConditions: [ 'node' ]
  vite:config     }
  vite:config   },
  vite:config   environments: {
  vite:config     client: {
  vite:config       define: undefined,
  vite:config       resolve: {
  vite:config         externalConditions: [ 'node' ],
  vite:config         extensions: [
  vite:config           '.mjs',  '.js',
  vite:config           '.mts',  '.ts',
  vite:config           '.jsx',  '.tsx',
  vite:config           '.json'
  vite:config         ],
  vite:config         dedupe: [],
  vite:config         noExternal: [],
  vite:config         external: [],
  vite:config         preserveSymlinks: false,
  vite:config         tsconfigPaths: false,
  vite:config         alias: [
  vite:config           {
  vite:config             find: /^\/?@vite\/env/,
  vite:config             replacement: '/@fs/Users/wojciech.maj/Downloads/repro/.yarn/__virtual__/rolldown-vite-virtual-0b8e2a0bcf/3/.yarn/berry/cache/rolldown-vite-npm-7.0.7-be200401d1-10c0.zip/node_modules/rolldown-vite/dist/client/env.mjs'
  vite:config           },
  vite:config           {
  vite:config             find: /^\/?@vite\/client/,
  vite:config             replacement: '/@fs/Users/wojciech.maj/Downloads/repro/.yarn/__virtual__/rolldown-vite-virtual-0b8e2a0bcf/3/.yarn/berry/cache/rolldown-vite-npm-7.0.7-be200401d1-10c0.zip/node_modules/rolldown-vite/dist/client/client.mjs'
  vite:config           }
  vite:config         ],
  vite:config         mainFields: [ 'browser', 'module', 'jsnext:main', 'jsnext' ],
  vite:config         conditions: [ 'module', 'browser', 'development|production' ],
  vite:config         builtins: []
  vite:config       },
  vite:config       keepProcessEnv: false,
  vite:config       consumer: 'client',
  vite:config       optimizeDeps: {
  vite:config         include: [],
  vite:config         exclude: [],
  vite:config         needsInterop: [],
  vite:config         rollupOptions: { resolve: { symlinks: true } },
  vite:config         extensions: [],
  vite:config         disabled: undefined,
  vite:config         holdUntilCrawlEnd: true,
  vite:config         force: false,
  vite:config         noDiscovery: false,
  vite:config         esbuildOptions: { preserveSymlinks: false }
  vite:config       },
  vite:config       dev: {
  vite:config         warmup: [],
  vite:config         sourcemap: { js: true },
  vite:config         sourcemapIgnoreList: [Function: isInNodeModules],
  vite:config         preTransformRequests: true,
  vite:config         createEnvironment: [Function: defaultCreateClientDevEnvironment],
  vite:config         recoverable: true,
  vite:config         moduleRunnerTransform: false
  vite:config       },
  vite:config       build: {
  vite:config         target: [ 'chrome107', 'edge107', 'firefox104', 'safari16' ],
  vite:config         polyfillModulePreload: true,
  vite:config         modulePreload: { polyfill: true },
  vite:config         outDir: 'dist',
  vite:config         assetsDir: 'assets',
  vite:config         assetsInlineLimit: 4096,
  vite:config         sourcemap: false,
  vite:config         terserOptions: {},
  vite:config         rollupOptions: { platform: 'browser' },
  vite:config         commonjsOptions: { include: [ /node_modules/ ], extensions: [ '.js', '.cjs' ] },
  vite:config         dynamicImportVarsOptions: { warnOnError: true, exclude: [ /node_modules/ ] },
  vite:config         write: true,
  vite:config         emptyOutDir: null,
  vite:config         copyPublicDir: true,
  vite:config         manifest: false,
  vite:config         lib: false,
  vite:config         ssrManifest: false,
  vite:config         ssrEmitAssets: false,
  vite:config         reportCompressedSize: true,
  vite:config         chunkSizeWarningLimit: 500,
  vite:config         watch: null,
  vite:config         cssCodeSplit: true,
  vite:config         minify: 'oxc',
  vite:config         ssr: false,
  vite:config         emitAssets: true,
  vite:config         createEnvironment: [Function: createEnvironment],
  vite:config         cssTarget: [ 'chrome107', 'edge107', 'firefox104', 'safari16' ],
  vite:config         cssMinify: true
  vite:config       },
  vite:config       plugins: [
  vite:config         {
  vite:config           name: 'vite:watch-package-data',
  vite:config           buildStart: [Function: buildStart],
  vite:config           buildEnd: [Function: buildEnd],
  vite:config           watchChange: [Function: watchChange]
  vite:config         },
  vite:config         {
  vite:config           name: 'alias',
  vite:config           buildStart: [AsyncFunction: buildStart],
  vite:config           resolveId: [Function: resolveId]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite-plugin-pwa',
  vite:config           enforce: 'pre',
  vite:config           config: [Function: config],
  vite:config           configResolved: [AsyncFunction: configResolved],
  vite:config           resolveId: [Function: resolveId],
  vite:config           load: [Function: load],
  vite:config           api: {
  vite:config             disabled: [Getter],
  vite:config             pwaInDevEnvironment: [Getter],
  vite:config             webManifestData: [Function: webManifestData],
  vite:config             registerSWData: [Function: registerSWData],
  vite:config             generateBundle: [Function: generateBundle],
  vite:config             generateSW: [AsyncFunction: generateSW],
  vite:config             extendManifestEntries: [Function: extendManifestEntries],
  vite:config             pwaAssetsGenerator: [Function: pwaAssetsGenerator]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:modulepreload-polyfill',
  vite:config           resolveId: {
  vite:config             filter: { id: /^vite\/modulepreload\-polyfill$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /^vite\/modulepreload\-polyfill\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:resolve',
  vite:config           resolveId: [AsyncFunction: resolveId],
  vite:config           load: {
  vite:config             filter: {
  vite:config               id: [
  vite:config                 /^__vite\-browser\-external/,
  vite:config                 /^__vite\-optional\-peer\-dep/
  vite:config               ]
  vite:config             },
  vite:config             handler: [Function: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:html-inline-proxy',
  vite:config           resolveId: {
  vite:config             filter: { id: /[?&]html-proxy\b/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /[?&]html-proxy\b/ },
  vite:config             handler: [Function: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:css',
  vite:config           buildStart: [Function: buildStart],
  vite:config           buildEnd: [Function: buildEnd],
  vite:config           load: {
  vite:config             filter: {
  vite:config               id: /\.(css|less|sass|scss|styl|stylus|pcss|postcss|sss)(?:$|\?)/
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 include: /\.(css|less|sass|scss|styl|stylus|pcss|postcss|sss)(?:$|\?)/,
  vite:config                 exclude: [
  vite:config                   /[?&]commonjs-proxy/,
  vite:config                   /[?&](?:worker|sharedworker|raw|url)\b/
  vite:config                 ]
  vite:config               }
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:oxc',
  vite:config           configureServer: [Function: configureServer],
  vite:config           resolveId: {
  vite:config             filter: { id: /^@oxc\-project\/runtime\// },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           transform: [AsyncFunction: transform]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:json',
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 include: /\.json(?:$|\?)(?!commonjs-(?:proxy|external))/,
  vite:config                 exclude: /[?&](?:worker|sharedworker|raw|url)\b/
  vite:config               },
  vite:config               moduleType: [ 'json' ]
  vite:config             },
  vite:config             handler: [Function: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:wasm-helper',
  vite:config           resolveId: {
  vite:config             filter: { id: /^vite\/wasm\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: {
  vite:config               id: [
  vite:config                 /^vite\/wasm\-helper\.js$/,
  vite:config                 /(?<![?#].*)\.wasm\?init/
  vite:config               ]
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:worker',
  vite:config           buildStart: [Function: buildStart],
  vite:config           load: {
  vite:config             filter: { id: /(?:\?|&)(worker|sharedworker)(?:&|$)/ },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           shouldTransformCachedModule: [Function: shouldTransformCachedModule],
  vite:config           transform: {
  vite:config             filter: { id: /(?:\?|&)worker_file&type=(\w+)(?:&|$)/ },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           renderChunk: [Function: renderChunk],
  vite:config           generateBundle: [Function: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:asset',
  vite:config           perEnvironmentStartEndDuringDev: true,
  vite:config           buildStart: [Function: buildStart],
  vite:config           resolveId: {
  vite:config             filter: {
  vite:config               id: [
  vite:config                 /(\?|&)url(?:&|$)/,
  vite:config                 /\.(apng|bmp|png|jpe?g|jfif|pjpeg|pjp|gif|svg|ico|webp|avif|cur|jxl|mp4|webm|ogg|mp3|wav|flac|aac|opus|mov|m4a|vtt|woff2?|eot|ttf|otf|webmanifest|pdf|txt)(\?.*)?$/i
  vite:config               ]
  vite:config             },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 include: [
  vite:config                   /(\?|&)raw(?:&|$)/,
  vite:config                   /(\?|&)url(?:&|$)/,
  vite:config                   /\.(apng|bmp|png|jpe?g|jfif|pjpeg|pjp|gif|svg|ico|webp|avif|cur|jxl|mp4|webm|ogg|mp3|wav|flac|aac|opus|mov|m4a|vtt|woff2?|eot|ttf|otf|webmanifest|pdf|txt)(\?.*)?$/i
  vite:config                 ],
  vite:config                 exclude: /^\0/
  vite:config               }
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           renderChunk: [Function: renderChunk],
  vite:config           generateBundle: [Function: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:wasm-fallback',
  vite:config           load: { filter: { id: /\.wasm$/ }, handler: [Function: handler] }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:define',
  vite:config           transform: { handler: [AsyncFunction: handler] }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:css-post',
  vite:config           renderStart: [Function: renderStart],
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 include: /\.(css|less|sass|scss|styl|stylus|pcss|postcss|sss)(?:$|\?)/,
  vite:config                 exclude: [
  vite:config                   /[?&]commonjs-proxy/,
  vite:config                   /[?&](?:worker|sharedworker|raw|url)\b/
  vite:config                 ]
  vite:config               }
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           renderChunk: [AsyncFunction: renderChunk],
  vite:config           augmentChunkHash: [Function: augmentChunkHash],
  vite:config           generateBundle: [AsyncFunction: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:build-html',
  vite:config           transform: {
  vite:config             filter: { id: /\.html$/ },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           generateBundle: [AsyncFunction: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:worker-import-meta-url',
  vite:config           applyToEnvironment: [Function: applyToEnvironment],
  vite:config           shouldTransformCachedModule: [Function: shouldTransformCachedModule],
  vite:config           transform: {
  vite:config             filter: {
  vite:config               code: /new\s+(?:Worker|SharedWorker).+new\s+URL.+import\.meta\.url/s
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:asset-import-meta-url',
  vite:config           applyToEnvironment: [Function: applyToEnvironment],
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 exclude: [
  vite:config                   /^vite\/preload\-helper\.js$/,
  vite:config                   /^\/Users\/wojciech\.maj\/Downloads\/repro\/\.yarn\/__virtual__\/rolldown\-vite\-virtual\-0b8e2a0bcf\/3\/\.yarn\/berry\/cache\/rolldown\-vite\-npm\-7\.0\.7\-be200401d1\-10c0\.zip\/node_modules\/rolldown\-vite\/dist\/client\/client\.mjs$/
  vite:config                 ]
  vite:config               },
  vite:config               code: /new\s+URL.+import\.meta\.url/
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         { name: 'vite:force-systemjs-wrap-complete' },
  vite:config         {
  vite:config           name: 'vite:dynamic-import-vars',
  vite:config           resolveId: {
  vite:config             filter: { id: /^vite\/dynamic\-import\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /^vite\/dynamic\-import\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 exclude: /^\/Users\/wojciech\.maj\/Downloads\/repro\/\.yarn\/__virtual__\/rolldown\-vite\-virtual\-0b8e2a0bcf\/3\/\.yarn\/berry\/cache\/rolldown\-vite\-npm\-7\.0\.7\-be200401d1\-10c0\.zip\/node_modules\/rolldown\-vite\/dist\/client\/client\.mjs$/
  vite:config               },
  vite:config               code: /\bimport\s*[(/]/
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:import-glob',
  vite:config           buildStart: [Function: buildStart],
  vite:config           transform: {
  vite:config             filter: { code: 'import.meta.glob' },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           hotUpdate: [Function: hotUpdate]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite-plugin-pwa:info',
  vite:config           enforce: 'post',
  vite:config           resolveId: [Function: resolveId],
  vite:config           load: [Function: load]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite-plugin-pwa:build',
  vite:config           enforce: 'post',
  vite:config           apply: 'build',
  vite:config           transformIndexHtml: {
  vite:config             order: 'post',
  vite:config             handler: [Function: handler],
  vite:config             enforce: 'post',
  vite:config             transform: [Function: transform]
  vite:config           },
  vite:config           generateBundle: [AsyncFunction: generateBundle],
  vite:config           closeBundle: {
  vite:config             sequential: true,
  vite:config             order: undefined,
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           buildEnd: [AsyncFunction: buildEnd]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite-plugin-pwa:pwa-assets',
  vite:config           enforce: 'post',
  vite:config           transformIndexHtml: {
  vite:config             order: 'post',
  vite:config             handler: [AsyncFunction: handler],
  vite:config             enforce: 'post',
  vite:config             transform: [AsyncFunction: transform]
  vite:config           },
  vite:config           resolveId: [Function: resolveId],
  vite:config           load: [AsyncFunction: load],
  vite:config           handleHotUpdate: [AsyncFunction: handleHotUpdate],
  vite:config           configureServer: [Function: configureServer]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:build-import-analysis',
  vite:config           resolveId: {
  vite:config             filter: { id: /^vite\/preload\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /^vite\/preload\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           transform: {
  vite:config             filter: { code: /import\s*\(/ },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           renderChunk: [Function: renderChunk],
  vite:config           generateBundle: [Function: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:oxc-transpile',
  vite:config           applyToEnvironment: [Function: applyToEnvironment],
  vite:config           renderChunk: [AsyncFunction: renderChunk]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:terser',
  vite:config           applyToEnvironment: [Function: applyToEnvironment],
  vite:config           renderChunk: [AsyncFunction: renderChunk],
  vite:config           closeBundle: [Function: closeBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:reporter',
  vite:config           sharedDuringBuild: true,
  vite:config           perEnvironmentStartEndDuringDev: true,
  vite:config           transform: [Function: transform],
  vite:config           buildStart: [Function: buildStart],
  vite:config           buildEnd: [Function: buildEnd],
  vite:config           renderStart: [Function: renderStart],
  vite:config           renderChunk: [Function: renderChunk],
  vite:config           generateBundle: [Function: generateBundle],
  vite:config           writeBundle: [AsyncFunction: writeBundle]
  vite:config         },
  vite:config         BuiltinPlugin {
  vite:config           name: 'builtin:load-fallback',
  vite:config           _options: undefined
  vite:config         }
  vite:config       ],
  vite:config       optimizeDepsPluginNames: []
  vite:config     },
  vite:config     ssr: {
  vite:config       define: undefined,
  vite:config       resolve: {
  vite:config         externalConditions: [ 'node' ],
  vite:config         extensions: [
  vite:config           '.mjs',  '.js',
  vite:config           '.mts',  '.ts',
  vite:config           '.jsx',  '.tsx',
  vite:config           '.json'
  vite:config         ],
  vite:config         dedupe: [],
  vite:config         noExternal: [ 'workbox-window' ],
  vite:config         external: [],
  vite:config         preserveSymlinks: false,
  vite:config         tsconfigPaths: false,
  vite:config         alias: [
  vite:config           {
  vite:config             find: /^\/?@vite\/env/,
  vite:config             replacement: '/@fs/Users/wojciech.maj/Downloads/repro/.yarn/__virtual__/rolldown-vite-virtual-0b8e2a0bcf/3/.yarn/berry/cache/rolldown-vite-npm-7.0.7-be200401d1-10c0.zip/node_modules/rolldown-vite/dist/client/env.mjs'
  vite:config           },
  vite:config           {
  vite:config             find: /^\/?@vite\/client/,
  vite:config             replacement: '/@fs/Users/wojciech.maj/Downloads/repro/.yarn/__virtual__/rolldown-vite-virtual-0b8e2a0bcf/3/.yarn/berry/cache/rolldown-vite-npm-7.0.7-be200401d1-10c0.zip/node_modules/rolldown-vite/dist/client/client.mjs'
  vite:config           }
  vite:config         ],
  vite:config         mainFields: [ 'module', 'jsnext:main', 'jsnext' ],
  vite:config         conditions: [ 'module', 'node', 'development|production' ],
  vite:config         builtins: [
  vite:config           '_http_agent',         '_http_client',        '_http_common',
  vite:config           '_http_incoming',      '_http_outgoing',      '_http_server',
  vite:config           '_stream_duplex',      '_stream_passthrough', '_stream_readable',
  vite:config           '_stream_transform',   '_stream_wrap',        '_stream_writable',
  vite:config           '_tls_common',         '_tls_wrap',           'assert',
  vite:config           'assert/strict',       'async_hooks',         'buffer',
  vite:config           'child_process',       'cluster',             'console',
  vite:config           'constants',           'crypto',              'dgram',
  vite:config           'diagnostics_channel', 'dns',                 'dns/promises',
  vite:config           'domain',              'events',              'fs',
  vite:config           'fs/promises',         'http',                'http2',
  vite:config           'https',               'inspector',           'inspector/promises',
  vite:config           'module',              'net',                 'os',
  vite:config           'path',                'path/posix',          'path/win32',
  vite:config           'perf_hooks',          'process',             'punycode',
  vite:config           'querystring',         'readline',            'readline/promises',
  vite:config           'repl',                'stream',              'stream/consumers',
  vite:config           'stream/promises',     'stream/web',          'string_decoder',
  vite:config           'sys',                 'timers',              'timers/promises',
  vite:config           'tls',                 'trace_events',        'tty',
  vite:config           'url',                 'util',                'util/types',
  vite:config           'v8',                  'vm',                  'wasi',
  vite:config           'worker_threads',      'zlib',                /^node:/,
  vite:config           /^npm:/,               /^bun:/
  vite:config         ]
  vite:config       },
  vite:config       keepProcessEnv: true,
  vite:config       consumer: 'server',
  vite:config       optimizeDeps: {
  vite:config         include: [],
  vite:config         exclude: [],
  vite:config         needsInterop: [],
  vite:config         rollupOptions: { resolve: { symlinks: true } },
  vite:config         extensions: [],
  vite:config         disabled: undefined,
  vite:config         holdUntilCrawlEnd: true,
  vite:config         force: false,
  vite:config         noDiscovery: true,
  vite:config         esbuildOptions: { preserveSymlinks: false }
  vite:config       },
  vite:config       dev: {
  vite:config         warmup: [],
  vite:config         sourcemap: { js: true },
  vite:config         sourcemapIgnoreList: [Function: isInNodeModules],
  vite:config         preTransformRequests: false,
  vite:config         createEnvironment: [Function: defaultCreateDevEnvironment],
  vite:config         recoverable: false,
  vite:config         moduleRunnerTransform: true
  vite:config       },
  vite:config       build: {
  vite:config         target: [ 'chrome107', 'edge107', 'firefox104', 'safari16' ],
  vite:config         polyfillModulePreload: true,
  vite:config         modulePreload: { polyfill: true },
  vite:config         outDir: 'dist',
  vite:config         assetsDir: 'assets',
  vite:config         assetsInlineLimit: 4096,
  vite:config         sourcemap: false,
  vite:config         terserOptions: {},
  vite:config         rollupOptions: { platform: 'node' },
  vite:config         commonjsOptions: { include: [ /node_modules/ ], extensions: [ '.js', '.cjs' ] },
  vite:config         dynamicImportVarsOptions: { warnOnError: true, exclude: [ /node_modules/ ] },
  vite:config         write: true,
  vite:config         emptyOutDir: null,
  vite:config         copyPublicDir: true,
  vite:config         manifest: false,
  vite:config         lib: false,
  vite:config         ssrManifest: false,
  vite:config         ssrEmitAssets: false,
  vite:config         reportCompressedSize: true,
  vite:config         chunkSizeWarningLimit: 500,
  vite:config         watch: null,
  vite:config         cssCodeSplit: true,
  vite:config         minify: false,
  vite:config         ssr: true,
  vite:config         emitAssets: true,
  vite:config         createEnvironment: [Function: createEnvironment],
  vite:config         cssTarget: [ 'chrome107', 'edge107', 'firefox104', 'safari16' ],
  vite:config         cssMinify: 'lightningcss'
  vite:config       },
  vite:config       plugins: [
  vite:config         {
  vite:config           name: 'vite:watch-package-data',
  vite:config           buildStart: [Function: buildStart],
  vite:config           buildEnd: [Function: buildEnd],
  vite:config           watchChange: [Function: watchChange]
  vite:config         },
  vite:config         {
  vite:config           name: 'alias',
  vite:config           buildStart: [AsyncFunction: buildStart],
  vite:config           resolveId: [Function: resolveId]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite-plugin-pwa',
  vite:config           enforce: 'pre',
  vite:config           config: [Function: config],
  vite:config           configResolved: [AsyncFunction: configResolved],
  vite:config           resolveId: [Function: resolveId],
  vite:config           load: [Function: load],
  vite:config           api: {
  vite:config             disabled: [Getter],
  vite:config             pwaInDevEnvironment: [Getter],
  vite:config             webManifestData: [Function: webManifestData],
  vite:config             registerSWData: [Function: registerSWData],
  vite:config             generateBundle: [Function: generateBundle],
  vite:config             generateSW: [AsyncFunction: generateSW],
  vite:config             extendManifestEntries: [Function: extendManifestEntries],
  vite:config             pwaAssetsGenerator: [Function: pwaAssetsGenerator]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:modulepreload-polyfill',
  vite:config           resolveId: {
  vite:config             filter: { id: /^vite\/modulepreload\-polyfill$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /^vite\/modulepreload\-polyfill\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:resolve',
  vite:config           resolveId: [AsyncFunction: resolveId],
  vite:config           load: {
  vite:config             filter: {
  vite:config               id: [
  vite:config                 /^__vite\-browser\-external/,
  vite:config                 /^__vite\-optional\-peer\-dep/
  vite:config               ]
  vite:config             },
  vite:config             handler: [Function: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:html-inline-proxy',
  vite:config           resolveId: {
  vite:config             filter: { id: /[?&]html-proxy\b/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /[?&]html-proxy\b/ },
  vite:config             handler: [Function: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:css',
  vite:config           buildStart: [Function: buildStart],
  vite:config           buildEnd: [Function: buildEnd],
  vite:config           load: {
  vite:config             filter: {
  vite:config               id: /\.(css|less|sass|scss|styl|stylus|pcss|postcss|sss)(?:$|\?)/
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 include: /\.(css|less|sass|scss|styl|stylus|pcss|postcss|sss)(?:$|\?)/,
  vite:config                 exclude: [
  vite:config                   /[?&]commonjs-proxy/,
  vite:config                   /[?&](?:worker|sharedworker|raw|url)\b/
  vite:config                 ]
  vite:config               }
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:oxc',
  vite:config           configureServer: [Function: configureServer],
  vite:config           resolveId: {
  vite:config             filter: { id: /^@oxc\-project\/runtime\// },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           transform: [AsyncFunction: transform]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:json',
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 include: /\.json(?:$|\?)(?!commonjs-(?:proxy|external))/,
  vite:config                 exclude: /[?&](?:worker|sharedworker|raw|url)\b/
  vite:config               },
  vite:config               moduleType: [ 'json' ]
  vite:config             },
  vite:config             handler: [Function: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:wasm-helper',
  vite:config           resolveId: {
  vite:config             filter: { id: /^vite\/wasm\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: {
  vite:config               id: [
  vite:config                 /^vite\/wasm\-helper\.js$/,
  vite:config                 /(?<![?#].*)\.wasm\?init/
  vite:config               ]
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:worker',
  vite:config           buildStart: [Function: buildStart],
  vite:config           load: {
  vite:config             filter: { id: /(?:\?|&)(worker|sharedworker)(?:&|$)/ },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           shouldTransformCachedModule: [Function: shouldTransformCachedModule],
  vite:config           transform: {
  vite:config             filter: { id: /(?:\?|&)worker_file&type=(\w+)(?:&|$)/ },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           renderChunk: [Function: renderChunk],
  vite:config           generateBundle: [Function: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:asset',
  vite:config           perEnvironmentStartEndDuringDev: true,
  vite:config           buildStart: [Function: buildStart],
  vite:config           resolveId: {
  vite:config             filter: {
  vite:config               id: [
  vite:config                 /(\?|&)url(?:&|$)/,
  vite:config                 /\.(apng|bmp|png|jpe?g|jfif|pjpeg|pjp|gif|svg|ico|webp|avif|cur|jxl|mp4|webm|ogg|mp3|wav|flac|aac|opus|mov|m4a|vtt|woff2?|eot|ttf|otf|webmanifest|pdf|txt)(\?.*)?$/i
  vite:config               ]
  vite:config             },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 include: [
  vite:config                   /(\?|&)raw(?:&|$)/,
  vite:config                   /(\?|&)url(?:&|$)/,
  vite:config                   /\.(apng|bmp|png|jpe?g|jfif|pjpeg|pjp|gif|svg|ico|webp|avif|cur|jxl|mp4|webm|ogg|mp3|wav|flac|aac|opus|mov|m4a|vtt|woff2?|eot|ttf|otf|webmanifest|pdf|txt)(\?.*)?$/i
  vite:config                 ],
  vite:config                 exclude: /^\0/
  vite:config               }
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           renderChunk: [Function: renderChunk],
  vite:config           generateBundle: [Function: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:wasm-fallback',
  vite:config           load: { filter: { id: /\.wasm$/ }, handler: [Function: handler] }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:define',
  vite:config           transform: { handler: [AsyncFunction: handler] }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:css-post',
  vite:config           renderStart: [Function: renderStart],
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 include: /\.(css|less|sass|scss|styl|stylus|pcss|postcss|sss)(?:$|\?)/,
  vite:config                 exclude: [
  vite:config                   /[?&]commonjs-proxy/,
  vite:config                   /[?&](?:worker|sharedworker|raw|url)\b/
  vite:config                 ]
  vite:config               }
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           renderChunk: [AsyncFunction: renderChunk],
  vite:config           augmentChunkHash: [Function: augmentChunkHash],
  vite:config           generateBundle: [AsyncFunction: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:build-html',
  vite:config           transform: {
  vite:config             filter: { id: /\.html$/ },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           generateBundle: [AsyncFunction: generateBundle]
  vite:config         },
  vite:config         { name: 'vite:force-systemjs-wrap-complete' },
  vite:config         {
  vite:config           name: 'vite:dynamic-import-vars',
  vite:config           resolveId: {
  vite:config             filter: { id: /^vite\/dynamic\-import\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /^vite\/dynamic\-import\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 exclude: /^\/Users\/wojciech\.maj\/Downloads\/repro\/\.yarn\/__virtual__\/rolldown\-vite\-virtual\-0b8e2a0bcf\/3\/\.yarn\/berry\/cache\/rolldown\-vite\-npm\-7\.0\.7\-be200401d1\-10c0\.zip\/node_modules\/rolldown\-vite\/dist\/client\/client\.mjs$/
  vite:config               },
  vite:config               code: /\bimport\s*[(/]/
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:import-glob',
  vite:config           buildStart: [Function: buildStart],
  vite:config           transform: {
  vite:config             filter: { code: 'import.meta.glob' },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           hotUpdate: [Function: hotUpdate]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite-plugin-pwa:info',
  vite:config           enforce: 'post',
  vite:config           resolveId: [Function: resolveId],
  vite:config           load: [Function: load]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite-plugin-pwa:build',
  vite:config           enforce: 'post',
  vite:config           apply: 'build',
  vite:config           transformIndexHtml: {
  vite:config             order: 'post',
  vite:config             handler: [Function: handler],
  vite:config             enforce: 'post',
  vite:config             transform: [Function: transform]
  vite:config           },
  vite:config           generateBundle: [AsyncFunction: generateBundle],
  vite:config           closeBundle: {
  vite:config             sequential: true,
  vite:config             order: undefined,
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           buildEnd: [AsyncFunction: buildEnd]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite-plugin-pwa:pwa-assets',
  vite:config           enforce: 'post',
  vite:config           transformIndexHtml: {
  vite:config             order: 'post',
  vite:config             handler: [AsyncFunction: handler],
  vite:config             enforce: 'post',
  vite:config             transform: [AsyncFunction: transform]
  vite:config           },
  vite:config           resolveId: [Function: resolveId],
  vite:config           load: [AsyncFunction: load],
  vite:config           handleHotUpdate: [AsyncFunction: handleHotUpdate],
  vite:config           configureServer: [Function: configureServer]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:build-import-analysis',
  vite:config           resolveId: {
  vite:config             filter: { id: /^vite\/preload\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /^vite\/preload\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           transform: {
  vite:config             filter: { code: /import\s*\(/ },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           renderChunk: [Function: renderChunk],
  vite:config           generateBundle: [Function: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:oxc-transpile',
  vite:config           applyToEnvironment: [Function: applyToEnvironment],
  vite:config           renderChunk: [AsyncFunction: renderChunk]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:reporter',
  vite:config           sharedDuringBuild: true,
  vite:config           perEnvironmentStartEndDuringDev: true,
  vite:config           transform: [Function: transform],
  vite:config           buildStart: [Function: buildStart],
  vite:config           buildEnd: [Function: buildEnd],
  vite:config           renderStart: [Function: renderStart],
  vite:config           renderChunk: [Function: renderChunk],
  vite:config           generateBundle: [Function: generateBundle],
  vite:config           writeBundle: [AsyncFunction: writeBundle]
  vite:config         },
  vite:config         BuiltinPlugin {
  vite:config           name: 'builtin:load-fallback',
  vite:config           _options: undefined
  vite:config         }
  vite:config       ],
  vite:config       optimizeDepsPluginNames: []
  vite:config     }
  vite:config   },
  vite:config   resolve: {
  vite:config     externalConditions: [ 'node' ],
  vite:config     extensions: [
  vite:config       '.mjs',  '.js',
  vite:config       '.mts',  '.ts',
  vite:config       '.jsx',  '.tsx',
  vite:config       '.json'
  vite:config     ],
  vite:config     dedupe: [],
  vite:config     noExternal: [],
  vite:config     external: [],
  vite:config     preserveSymlinks: false,
  vite:config     tsconfigPaths: false,
  vite:config     alias: [
  vite:config       {
  vite:config         find: /^\/?@vite\/env/,
  vite:config         replacement: '/@fs/Users/wojciech.maj/Downloads/repro/.yarn/__virtual__/rolldown-vite-virtual-0b8e2a0bcf/3/.yarn/berry/cache/rolldown-vite-npm-7.0.7-be200401d1-10c0.zip/node_modules/rolldown-vite/dist/client/env.mjs'
  vite:config       },
  vite:config       {
  vite:config         find: /^\/?@vite\/client/,
  vite:config         replacement: '/@fs/Users/wojciech.maj/Downloads/repro/.yarn/__virtual__/rolldown-vite-virtual-0b8e2a0bcf/3/.yarn/berry/cache/rolldown-vite-npm-7.0.7-be200401d1-10c0.zip/node_modules/rolldown-vite/dist/client/client.mjs'
  vite:config       }
  vite:config     ],
  vite:config     mainFields: [ 'browser', 'module', 'jsnext:main', 'jsnext' ],
  vite:config     conditions: [ 'module', 'browser', 'development|production' ],
  vite:config     builtins: []
  vite:config   },
  vite:config   configFile: '/Users/wojciech.maj/Downloads/repro/vite.config.ts',
  vite:config   configFileDependencies: [ '/Users/wojciech.maj/Downloads/repro/rolldown:runtime' ],
  vite:config   inlineConfig: {
  vite:config     root: undefined,
  vite:config     base: undefined,
  vite:config     mode: undefined,
  vite:config     configFile: undefined,
  vite:config     configLoader: undefined,
  vite:config     logLevel: undefined,
  vite:config     clearScreen: undefined,
  vite:config     build: {}
  vite:config   },
  vite:config   root: '/Users/wojciech.maj/Downloads/repro',
  vite:config   base: '/',
  vite:config   decodedBase: '/',
  vite:config   rawBase: '/',
  vite:config   publicDir: '/Users/wojciech.maj/Downloads/repro/public',
  vite:config   cacheDir: '/Users/wojciech.maj/Downloads/repro/node_modules/.vite',
  vite:config   command: 'build',
  vite:config   mode: 'production',
  vite:config   isWorker: false,
  vite:config   mainConfig: null,
  vite:config   bundleChain: [],
  vite:config   isProduction: true,
  vite:config   css: {
  vite:config     transformer: 'postcss',
  vite:config     preprocessorMaxWorkers: true,
  vite:config     devSourcemap: false
  vite:config   },
  vite:config   json: { namedExports: true, stringify: 'auto' },
  vite:config   esbuild: { jsxDev: false },
  vite:config   oxc: { jsx: { development: false } },
  vite:config   server: {
  vite:config     port: 5173,
  vite:config     strictPort: false,
  vite:config     host: undefined,
  vite:config     allowedHosts: [],
  vite:config     https: undefined,
  vite:config     open: false,
  vite:config     proxy: undefined,
  vite:config     cors: {
  vite:config       origin: /^https?:\/\/(?:(?:[^:]+\.)?localhost|127\.0\.0\.1|\[::1\])(?::\d+)?$/
  vite:config     },
  vite:config     headers: {},
  vite:config     warmup: { clientFiles: [], ssrFiles: [] },
  vite:config     middlewareMode: false,
  vite:config     fs: {
  vite:config       strict: true,
  vite:config       deny: [ '.env', '.env.*', '*.{crt,pem}', '**/.git/**' ],
  vite:config       allow: [
  vite:config         '/Users/wojciech.maj/Downloads/repro',
  vite:config         '/Users/wojciech.maj/.yarn/berry'
  vite:config       ]
  vite:config     },
  vite:config     preTransformRequests: true,
  vite:config     perEnvironmentStartEndDuringDev: false,
  vite:config     sourcemapIgnoreList: [Function: isInNodeModules]
  vite:config   },
  vite:config   builder: undefined,
  vite:config   preview: {
  vite:config     port: 4173,
  vite:config     strictPort: false,
  vite:config     host: undefined,
  vite:config     allowedHosts: [],
  vite:config     https: undefined,
  vite:config     open: false,
  vite:config     proxy: undefined,
  vite:config     cors: {
  vite:config       origin: /^https?:\/\/(?:(?:[^:]+\.)?localhost|127\.0\.0\.1|\[::1\])(?::\d+)?$/
  vite:config     },
  vite:config     headers: {}
  vite:config   },
  vite:config   envDir: '/Users/wojciech.maj/Downloads/repro',
  vite:config   env: { BASE_URL: '/', MODE: 'production', DEV: false, PROD: true },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   rawAssetsInclude: [],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(1) {
  vite:config     'fnpd_/Users/wojciech.maj/Downloads/repro' => {
  vite:config       dir: '/Users/wojciech.maj/Downloads/repro',
  vite:config       data: {
  vite:config         name: 'repro',
  vite:config         scripts: { build: 'vite build', dev: 'vite' },
  vite:config         dependencies: {
  vite:config           vite: 'npm:rolldown-vite@7.0.7',
  vite:config           'vite-plugin-pwa': '^1.0.1'
  vite:config         },
  vite:config         packageManager: 'yarn@4.9.1'
  vite:config       },
  vite:config       hasSideEffects: [Function: hasSideEffects],
  vite:config       setResolvedCache: [Function: setResolvedCache],
  vite:config       getResolvedCache: [Function: getResolvedCache]
  vite:config     },
  vite:config     set: [Function (anonymous)]
  vite:config   },
  vite:config   worker: { format: 'iife', plugins: '() => plugins', rollupOptions: {} },
  vite:config   appType: 'spa',
  vite:config   experimental: {
  vite:config     importGlobRestoreExtension: false,
  vite:config     renderBuiltUrl: undefined,
  vite:config     hmrPartialAccept: false,
  vite:config     enableNativePlugin: false
  vite:config   },
  vite:config   future: undefined,
  vite:config   optimizeDeps: {
  vite:config     include: [],
  vite:config     exclude: [],
  vite:config     needsInterop: [],
  vite:config     rollupOptions: { resolve: { symlinks: true } },
  vite:config     extensions: [],
  vite:config     disabled: undefined,
  vite:config     holdUntilCrawlEnd: true,
  vite:config     force: false,
  vite:config     noDiscovery: false,
  vite:config     esbuildOptions: { preserveSymlinks: false }
  vite:config   },
  vite:config   dev: {
  vite:config     warmup: [],
  vite:config     sourcemap: { js: true },
  vite:config     sourcemapIgnoreList: [Function: isInNodeModules],
  vite:config     preTransformRequests: false,
  vite:config     createEnvironment: [Function: defaultCreateDevEnvironment],
  vite:config     recoverable: false,
  vite:config     moduleRunnerTransform: false
  vite:config   },
  vite:config   webSocketToken: '5PYah386ng3b',
  vite:config   getSortedPlugins: [Function: getSortedPlugins],
  vite:config   getSortedPluginHooks: [Function: getSortedPluginHooks],
  vite:config   createResolver: [Function: createResolver],
  vite:config   fsDenyGlob: [Function: arrayMatcher],
  vite:config   safeModulePaths: Set(0) {},
  vite:config   Symbol(vite:resolved-config): true
  vite:config } +654ms
rolldown-vite v7.0.7 building for production...
✓ 5 modules transformed.
dist/manifest.webmanifest      0.15 kB
dist/index.html                0.24 kB │ gzip: 0.20 kB
dist/assets/index-voRYvffs.js  2.96 kB │ gzip: 1.40 kB
<anonymous_script>:0


Error: [vite]: Rollup failed to resolve import "workbox-window" from "/@vite-plugin-pwa/virtual:pwa-register".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteLog (file:///Users/wojciech.maj/Downloads/repro/.yarn/__virtual__/rolldown-vite-virtual-0b8e2a0bcf/3/.yarn/berry/cache/rolldown-vite-npm-7.0.7-be200401d1-10c0.zip/node_modules/rolldown-vite/dist/node/chunks/dep-DnpJBiTH.js:33465:57)
    at onRollupLog (file:///Users/wojciech.maj/Downloads/repro/.yarn/__virtual__/rolldown-vite-virtual-0b8e2a0bcf/3/.yarn/berry/cache/rolldown-vite-npm-7.0.7-be200401d1-10c0.zip/node_modules/rolldown-vite/dist/node/chunks/dep-DnpJBiTH.js:33501:9)
    at onLog (file:///Users/wojciech.maj/Downloads/repro/.yarn/__virtual__/rolldown-vite-virtual-0b8e2a0bcf/3/.yarn/berry/cache/rolldown-vite-npm-7.0.7-be200401d1-10c0.zip/node_modules/rolldown-vite/dist/node/chunks/dep-DnpJBiTH.js:33269:4)
    at file:///Users/wojciech.maj/.yarn/berry/cache/rolldown-npm-1.0.0-beta.25-62fd694bda-10c0.zip/node_modules/rolldown/dist/shared/src-BS7SHs-K.mjs:192:26
    at logger (file:///Users/wojciech.maj/.yarn/berry/cache/rolldown-npm-1.0.0-beta.25-62fd694bda-10c0.zip/node_modules/rolldown/dist/shared/src-BS7SHs-K.mjs:183:3)

Node.js v24.3.0
```
</details>

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/rolldown-vite/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/rolldown-vite/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide) and the [Rolldown-related guide](https://main.vite.dev/guide/rolldown.html).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/rolldown-vite/issues) that reports the same regression to avoid creating a duplicate.
- [x] Check that this is a concrete regression. For Q&A open a [GitHub Discussion](https://github.com/vitejs/rolldown-vite/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the regression.

**Comment by wojtekmaj** [comment]
Still reproducible in v7.1.2.

I dug a little deeper and here's what I found:

- `virtual:pwa-register` gets replaced with contents of `node_modules/vite-plugin-pwa/dist/client/build/register.js` via `load` hook
- Problematic `register.js` contains:
  ```js
      wb = await import("workbox-window").then(({ Workbox }) => {
        return new Workbox("/sw.js", { scope: "/", type: "classic" });
      }).catch((e) => {
        onRegisterError?.(e);
        return void 0;
      });
  ```
- When I hack `vite-plugin-pwa` to resolve `virtual:pwa-register` to `node_modules/vite-plugin-pwa/dist/client/build/register.js` in `resolveId` hook, then everything appears to work (aside from some additional logic `load` hook does in this plugin
- Unplugging `vite-plugin-pwa` and/or `workbox-window` doesn't change anything, interestingly

So it looks like: **module resolution fails in Yarn PnP on module contents injected via `load` hook.**

**Comment by Boshen** [comment]
This issue has nothing to do with `yarn`.

Using pnpm, log:

```
DEBUG oxc_resolver: options: ResolveOptions { cwd: Some("/Users/boshen/reproductions/repro"), tsconfig: None, alias: [], alias_fields: [["browser"]], condition_names: ["import", "default", "module", "browser"], enforce_extension: Disabled, exports_fields: [["exports"]], imports_fields: [["imports"]], extension_alias: [(".js", [".js", ".ts", ".tsx"]), (".jsx", [".jsx", ".ts", ".tsx"]), (".mjs", [".mjs", ".mts"]), (".cjs", [".cjs", ".cts"])], extensions: [".tsx", ".ts", ".jsx", ".js", ".json"], fallback: [], fully_specified: false, main_fields: ["browser", "module", "main"], main_files: ["index"], modules: ["node_modules"], resolve_to_context: false, prefer_relative: false, prefer_absolute: false, restrictions: [], roots: [], symlinks: true, builtin_modules: false, module_type: true, allow_package_exports_in_directory_resolve: false, yarn_pnp: false }, path: "/@vite-plugin-pwa", specifier: "workbox-window", err: NotFound("workbox-window")
```

I don't know anything about virtual modules `path: "/@vite-plugin-pwa"`, so handing this back to you @sapphi-red, or maybe @shulaoda?

**Comment by sapphi-red** [comment]
I got the same error with normal Vite:
```
[vite-plugin-pwa:build] [plugin vite-plugin-pwa:build] There was an error during the build:
  [vite]: Rollup failed to resolve import "workbox-window" from "/@vite-plugin-pwa/virtual:pwa-register".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```
, and this is an expected error. For virtual modules, the packages are resolved from the `root`. This means `workbox-window` needs to be a dependency of the project.

It seems this is documented on plugin-pwa's docs:

> You will need to add `workbox-window` as a `dev` dependency to your Vite project.
> https://vite-pwa-org.netlify.app/frameworks/react.html#react

**Comment by sapphi-red** [comment]
The reason it works with `yarn config set nodeLinker node-modules` is because of the hoisting.

**Comment by wojtekmaj** [comment]
I wish it was correct, but it's not. I have added workbox-window to devDependencies and it still fails.

The "classic" Vite also works with:

```
packageExtensions:
  my-project@1.0.0:
    dependencies:
      workbox-window: ^7.1.0
```

but Rolldown-based, does not.

Logs from adding workbox-window directly as a dev dependency + building:

```
wojciech.maj@MacBook-Pro app % YARN_NODE_LINKER=pnp yarn add workbox-window --dev
➤ YN0000: · Yarn 4.10.3
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ vite is listed by your project with version 8.0.0-beta.0 (pc0fb15), which doesn't satisfy what @vitejs/plugin-basic-ssl and other dependencies request (^6.0.0 || ^7.0.0).
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 357ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 0s 548ms

wojciech.maj@MacBook-Pro app % YARN_NODE_LINKER=pnp yarn build
vite v8.0.0-beta.0 building client environment for production...
✓ 4070 modules transformed.
[vite-plugin-static-copy] Copied 3 items.
dist/index.html                                      6.91 kB │ gzip:   1.59 kB
(redacted)
✗ Build failed in 1.47s

PWA v1.2.0
mode      generateSW
precache  73 entries (3187.63 KiB)
files generated
  dist/service-worker.js.map
  dist/service-worker.js
  dist/workbox-829c7195.js.map
  dist/workbox-829c7195.js
error during build:
Build failed with 1 error:

Error: [vite]: Rolldown failed to resolve import "workbox-window" from "/@vite-plugin-pwa/virtual:pwa-register".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteLog (file:///app/.yarn/__virtual__/vite-virtual-7a79a0d8c5/0/cache/vite-npm-8.0.0-beta.0-3ad3bc975d-cf41c574d7.zip/node_modules/vite/dist/node/chunks/node.js:32892:57)
    at file:///app/.yarn/__virtual__/vite-virtual-7a79a0d8c5/0/cache/vite-npm-8.0.0-beta.0-3ad3bc975d-cf41c574d7.zip/node_modules/vite/dist/node/chunks/node.js:32928:73
    at onwarn (file:///app/.yarn/__virtual__/@vitejs-plugin-react-virtual-72919e78ba/0/cache/@vitejs-plugin-react-npm-5.1.1-f09db76823-e590efaea1.zip/node_modules/@vitejs/plugin-react/dist/index.js:76:7)
    at file:///app/.yarn/__virtual__/vite-virtual-7a79a0d8c5/0/cache/vite-npm-8.0.0-beta.0-3ad3bc975d-cf41c574d7.zip/node_modules/vite/dist/node/chunks/node.js:32928:28
    at onRollupLog (file:///app/.yarn/__virtual__/vite-virtual-7a79a0d8c5/0/cache/vite-npm-8.0.0-beta.0-3ad3bc975d-cf41c574d7.zip/node_modules/vite/dist/node/chunks/node.js:32923:63)
    at onLog (file:///app/.yarn/__virtual__/vite-virtual-7a79a0d8c5/0/cache/vite-npm-8.0.0-beta.0-3ad3bc975d-cf41c574d7.zip/node_modules/vite/dist/node/chunks/node.js:32691:4)
    at file:///app/.yarn/cache/rolldown-npm-1.0.0-beta.53-db59d0aaea-363109aa38.zip/node_modules/rolldown/dist/shared/rolldown-build-BEU8N80I.mjs:47:26
    at logger (file:///app/.yarn/cache/rolldown-npm-1.0.0-beta.53-db59d0aaea-363109aa38.zip/node_modules/rolldown/dist/shared/rolldown-build-BEU8N80I.mjs:38:3)
    at onLog (file:///app/.yarn/cache/rolldown-npm-1.0.0-beta.53-db59d0aaea-363109aa38.zip/node_modules/rolldown/dist/shared/bindingify-input-options-Bk0BBr2s.mjs:1366:32)
    at aggregateBindingErrorsIntoJsError (file:///app/.yarn/cache/rolldown-npm-1.0.0-beta.53-db59d0aaea-363109aa38.zip/node_modules/rolldown/dist/shared/bindingify-input-options-Bk0BBr2s.mjs:56:18)
    at unwrapBindingResult (file:///app/.yarn/cache/rolldown-npm-1.0.0-beta.53-db59d0aaea-363109aa38.zip/node_modules/rolldown/dist/shared/bindingify-input-options-Bk0BBr2s.mjs:31:128)
    at #build (file:///app/.yarn/cache/rolldown-npm-1.0.0-beta.53-db59d0aaea-363109aa38.zip/node_modules/rolldown/dist/shared/rolldown-build-BEU8N80I.mjs:2260:34)
    at async buildEnvironment (file:///app/.yarn/__virtual__/vite-virtual-7a79a0d8c5/0/cache/vite-npm-8.0.0-beta.0-3ad3bc975d-cf41c574d7.zip/node_modules/vite/dist/node/chunks/node.js:32799:64)
    at async Object.build (file:///app/.yarn/__virtual__/vite-virtual-7a79a0d8c5/0/cache/vite-npm-8.0.0-beta.0-3ad3bc975d-cf41c574d7.zip/node_modules/vite/dist/node/chunks/node.js:33202:19)
    at async Object.buildApp (file:///app/.yarn/__virtual__/vite-virtual-7a79a0d8c5/0/cache/vite-npm-8.0.0-beta.0-3ad3bc975d-cf41c574d7.zip/node_modules/vite/dist/node/chunks/node.js:33199:153)
    at async CAC.<anonymous> (file:///app/.yarn/__virtual__/vite-virtual-7a79a0d8c5/0/cache/vite-npm-8.0.0-beta.0-3ad3bc975d-cf41c574d7.zip/node_modules/vite/dist/node/cli.js:629:3)
```

**Comment by sapphi-red** [comment]
The issue related to pnp itself will be fixed in the next version.
